import type { Metadata } from "next";
import localFont from "next/font/local";
import I18nServer from "@/app/components/i18n-server";
import { getLocaleOnServer } from "@/i18n/server"

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = getLocaleOnServer();
  return (
    <html lang={locale ?? "en"}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <I18nServer>{children}</I18nServer>
      </body>
    </html>
  );
}
